export default [
	"1st server",
	"999.1",
	"999",
	"999Apartment",
	"999CaptainsQuarters",
	"999Cargo",
	"999Casino",
	"999Cdeck",
	"999CentralStairs",
	"999Chapel",
	"999Chart",
	"999Confinement",
	"999DoorsA",
	"999DoorsB",
	"999Hospital",
	"999Kitchen",
	"999Library",
	"999Operating",
	"999Shower",
	"999Steam",
	"999Steeldoor",
	"999Study",
	"999Torture",
	"9991stClassCabinA",
	"9991stClassCabinB",
	"9992ndClassCabin",
	"AA - Edgewort's Office",
	"AA - Gantsroom",
	"AA - Gatewater room",
	"AA - Gourd Lake",
	"AA - Gourd Lake Entrance",
	"AA - Hotel Lobby",
	"AA - Hotticlinic",
	"AA - Kurain",
	"AA - Parkinglot",
	"AA - Police Deparment",
	"AA - Police Station",
	"AA - Records Room",
	"AA - Sc13",
	"AA - Wright's Office",
	"AABluecorp",
	"AACourt",
	"AACourtAnime",
	"AACourtChristmasDecorations",
	"AACourtChristmasLights",
	"AACourtHD",
	"AADefendantLobby",
	"AADefendantLobbyHD",
	"AADetentionCenter",
	"AAEdgeworthOffice",
	"AAGantOffice",
	"AAGatewaterHotel",
	"AAGlobalStudiosEast",
	"AAGlobalStudiosWest",
	"AAGourdLake",
	"AAGrossbergOffice",
	"AAI2Circus",
	"AAI2City",
	"AAI2GourdLake",
	"AAI2LogicChess",
	"AAI2MuseumPast",
	"AAI2MuseumPresent",
	"AAI2PIC",
	"AAI2Prison",
	"AAICohdopianEmbassy",
	"AAICourt",
	"AAICourtFlipped",
	"AAIEdgeworthOffice",
	"AAIGatewaterLandStage",
	"AAIGatewaterLandWildWest",
	"AAIiFlyAirlines",
	"AALobby",
	"AAParkingLot",
	"AAPoliceStation",
	"AATrainStation",
	"AAWrightOffice",
	"AJBorschtBowlClub",
	"AJCourt",
	"AJCourtBirthday",
	"AJCourtHalloween",
	"AJCourtNight",
	"AJCourtTV",
	"AJDefendantLobby",
	"AJDetentionCenter",
	"AJDrewStudio",
	"AJHottiClinic",
	"AJKlavierOffice",
	"AJKristophCell",
	"AJLobby",
	"AJMeraktisClinic",
	"AJPeoplePark",
	"AJSunshineColiseum",
	"AJWrightOffice",
	"Ace",
	"AcroRoomJFA",
	"AirportJFA",
	"AlbaOfficeAAI",
	"Anime",
	"Arcade",
	"AtmeyOfficeTT",
	"Atrium (SG)",
	"AutumnForest",
	"BB - Flowerfield",
	"BB - Market",
	"BB - Street",
	"BandoLandAAI",
	"Basement",
	"Battlegrounds",
	"BerryBigCircusJFA",
	"Blackout",
	"BlueScreensTT",
	"BluecorpAA",
	"BridgeNest",
	"Brig",
	"Building",
	"CC1",
	"CC2",
	"CC3",
	"CC4",
	"CC5",
	"CC6",
	"CC7",
	"CC8",
	"CC9",
	"CC10",
	"CC11",
	"CC12",
	"CO - Big door",
	"CO - Finalroom",
	"CO - Meetingroom",
	"CO - Whitedoor",
	"CO - Whitelobby",
	"CO - Whitelowerfloor",
	"CO - White room",
	"CP",
	"CPRP2 Chap1",
	"CPRP2 Chap2and3",
	"CPRP2 Chap4",
	"CPRP2 Chap5",
	"CPRP Chap1",
	"CPRP Chap2",
	"CPRP Chap3",
	"CPRP Chap4",
	"CPRP Chap5",
	"CVStMystere",
	"Cafe",
	"CafeCourt",
	"CaffeeCase",
	"Cal",
	"CargoHoldAAI",
	"Casino",
	"CasinoCourt",
	"Cathedral (SG)",
	"Christmas",
	"Christmas Courtroom",
	"CinemaFamousi",
	"Classroom",
	"Co - Lobby 1",
	"Co - Lobby 2",
	"CochenOfficeAAI",
	"ColosseumFerox",
	"Control Room",
	"Control Room Interior",
	"CountyCourt",
	"CourtroomAA",
	"CourtroomAAHD",
	"CourtroomAAI",
	"CourtroomAJ",
	"CourtroomAJNight",
	"CourtroomAnime",
	"CourtroomCounty",
	"CourtroomDD",
	"CourtroomEnglish",
	"CourtroomNew",
	"CourtroomRuined",
	"CourtroomThemis",
	"CourtroomTouhou",
	"CourtroomWitch",
	"CruiseCourt",
	"CustomEight",
	"CustomEleven",
	"CustomFifteen",
	"CustomFive",
	"CustomFour",
	"CustomFourteen",
	"CustomNine",
	"CustomOne",
	"CustomSeven",
	"CustomSix",
	"CustomTen",
	"CustomThirteen",
	"CustomThree",
	"CustomTwelve",
	"CustomTwo",
	"DC",
	"DDCourt",
	"DDCourtGray",
	"DDCourtRuined",
	"DDCourtRuinedInvestigation",
	"DDCourtThemis",
	"DDDefendantLobby",
	"DDGyaxa",
	"DDLobby",
	"DDNinetailsVale",
	"DDShipshapeAquarium",
	"DDThemisAcademy",
	"DFreightTrain",
	"DGS-ENG",
	"DGS-JAP",
	"DGS",
	"DGSCourtJapanese",
	"DGSCourtOldBailey",
	"DGSCourtOldBaileyJury",
	"DGSDefendantLobbyJapanese",
	"DGSDefendantLobbyOldBailey",
	"DGSEnglishCourt",
	"DGSJapanCourt",
	"DGSLondon",
	"DGSenglishcourt",
	"DRAE-Area1",
	"DRAE-Area2",
	"DRClassTrial",
	"DRRP",
	"Dark Cave",
	"Darkness",
	"Datrone Heart",
	"Datrone HeartHQ",
	"DeLiteHouseTT",
	"Despair vs. Hope",
	"DetentionCenterAAI2",
	"DimensionalGate",
	"DogenCellAAI2",
	"DualDestinies",
	"Dungeon Courtroom",
	"EdgeworthOfficeAA",
	"EdgeworthOfficeAAI",
	"EmbassyAAI",
	"Endless Courtroom",
	"EngardeManorJFA",
	"EnglishCourt",
	"Errors",
	"Errors2",
	"FECastle",
	"FECave",
	"FEFort",
	"FEPlain",
	"FETavern",
	"Factory",
	"FieldFortune",
	"FilmSetAAI2",
	"Flowerfield",
	"ForensicCourt",
	"Forest",
	"GS4Night",
	"GantOfficeAA",
	"GetwaterHotelJFA",
	"GetwaterStageJFA",
	"GlobalStudiosIndoorsAA",
	"GlobalStudiosOutdoorsAA",
	"GourdLakeAA",
	"GrandChokmah",
	"GrandStadium",
	"Graveyard",
	"GreatWitchtrialCourt",
	"GrossbergOfficeAA",
	"HD",
	"HQFarm",
	"HQHalloweenTown",
	"HQHolodeck",
	"HQShrine",
	"HQTown",
	"HQVolcanoCherry",
	"HallOfFame",
	"HarborTown",
	"HarvestFestival",
	"HazakuraTemple1TT",
	"HazakuraTemple2TT",
	"Headquarters",
	"Headquarters 2",
	"Hell Correspondence",
	"Hospital",
	"HotelRoomAA",
	"HottiClinicJFA",
	"Innsmouth",
	"InsidePlaneAAI2",
	"Interiors (Day)",
	"Interiors (Night)",
	"JFAAirport",
	"JFABerryBigCircusEast",
	"JFABerryBigCircusWest",
	"JFAGatewaterHotel",
	"JFAHottiClinic",
	"JFAKurainVillage",
	"JFAMattHouse",
	"JapaneseCourt",
	"Kamurocho (Day)",
	"Kamurocho (Night)",
	"Keterburg",
	"Khura'in",
	"Khurain",
	"KokonoeLab",
	"KurainCourt",
	"KurainVillageJFA",
	"LBCastle",
	"LBMisc",
	"LBScotlandYard",
	"Lab 8",
	"Lentomain",
	"Library",
	"LogicChessAAI2",
	"MI - Ashleys Shack",
	"MLP - Apple barn",
	"MLP - CMC Clubhouse",
	"MLP - CMC Clubhouse inside",
	"MLP - Canterlot Castle galaroom",
	"MLP - Canterlot Hallway",
	"MLP - Canterlot Library2",
	"MLP - Canterlot Town",
	"MLP - Canterlot alley",
	"MLP - Canterlot library",
	"MLP - Carousel Boutique",
	"MLP - Clearing",
	"MLP - Curio Shop",
	"MLP - Everfree Forest",
	"MLP - Everfree Forest entrance",
	"MLP - Fluttershy's cottage",
	"MLP - Hospital Room",
	"MLP - Hotelroom",
	"MLP - Library 2F",
	"MLP - Library mainfloor",
	"MLP - Old Castle",
	"MLP - Orchard",
	"MLP - PV Hospital",
	"MLP - PV Street",
	"MLP - Ponyville",
	"MLP - Shining's apartment",
	"MLP - Sugarcube Corner",
	"MLP - Twilight's Lab",
	"MM - Castle",
	"MM - Madokas house",
	"MM - School yard",
	"MM - Street",
	"MM - Street2",
	"MM - classroom",
	"MM - dark hallway",
	"MM - rooftop",
	"MM - room whit Kyubey",
	"MM - school hallway",
	"MM - staircase",
	"MMA-Bedrooms1",
	"MMA-Floor 1",
	"MS - Cathedral",
	"MS - Zakum's Tree",
	"Mansion",
	"MansionAAI2",
	"MansionHQ",
	"Maplecrest - Nightmare",
	"Maplecrest",
	"Market",
	"Mayonaka",
	"MechHangar",
	"Medici Tower",
	"Military Base Exterior",
	"MoeRoomJFA",
	"MuseumAAI2",
	"MuseumTT",
	"Music",
	"NewCourt",
	"New Meridian",
	"Ninetailsvale",
	"Nordon Plains",
	"Nordon Plains Night",
	"OCArcade",
	"OCBebop",
	"OCCourtCafe",
	"OCCourtCounty",
	"OCCourtCruise",
	"OCCourtEndless",
	"OCCourtFinalDestination",
	"OCCourtInverted",
	"OCCourtPirateShip",
	"OCCourtSky",
	"OCCourtSpace",
	"OCCourtSpaceShip",
	"OCCourtTouhou",
	"OCCourtZetta",
	"OCDungeon",
	"OCHospital",
	"OCRoad",
	"OCTownPirate",
	"OCTownShanty",
	"OCWhiteRoom",
	"OfficeHouseHQ",
	"OfficeNightAA",
	"Osaka (Night)",
	"Osaka",
	"OutsidePlaneAAI2",
	"P4UBasement",
	"P4ULab",
	"P4Ubaseball",
	"P4Ubeach",
	"P4Ubuilding",
	"P4Uconcert",
	"P4Ugarden",
	"P4Ugraveyard",
	"P4Uhell",
	"P4Ujail",
	"P4Umisc",
	"P4Unight",
	"P4Uoffices",
	"P4Urailway",
	"P4Urestaurants",
	"P4Urooms",
	"P4Uruins",
	"P4Uschool",
	"P4Ustage1",
	"P4Ustage2",
	"P4Ustation",
	"P4Ustore",
	"P4Utent",
	"P4Utransport",
	"P4Utv",
	"P4Uvelvetroom",
	"PICAAI2",
	"PLvsAAAlchemistHouse",
	"PLvsAABellTower",
	"PLvsAACastle",
	"PLvsAACourtEnglish",
	"PLvsAACourtLabyrinthia",
	"PLvsAACourthouse",
	"PLvsAADefendantLobbyEnglish",
	"PLvsAADefendantLobbyLabyrinthia",
	"PLvsAAEclaireBakery",
	"PLvsAAForest",
	"PLvsAAGreatArchive",
	"PLvsAALabyrinthiaInner",
	"PLvsAALabyrinthiaOuter",
	"PLvsAALondon",
	"PLvsAARougeTavern",
	"PLvsAARuins",
	"PLvsAAStorytellerTower",
	"PLvsAAWagon",
	"PLvsAAWorkshop",
	"PMMMRP",
	"PMMMWitch",
	"ParkingLotAA",
	"PeonyCastle",
	"Persona Afternoon",
	"Persona DH",
	"Persona Morning",
	"Persona Night",
	"PersonaRP",
	"PhoenixOfficeAA",
	"PirateShip",
	"PlaneAAI",
	"PlaneLoungeAAI",
	"PlaneLoungeLandAAI",
	"PlatPark",
	"PlatRemnant",
	"PlatunaArea1",
	"PlatunaArea1HQ",
	"PlatunaArea2",
	"PlatunaArea2HQ",
	"PlatunaMain",
	"PlatunamainHQ",
	"PrecinctAA",
	"PrisonAAI2",
	"PrisonCourtyardAAI2",
	"RG - 104",
	"RG - A-East",
	"RG - AMX",
	"RG - Bus Terminal",
	"RG - Cadoi City",
	"RG - Concert",
	"RG - Dogenzaka",
	"RG - God Pad",
	"RG - Miyashita Underpass",
	"RG - Station Underpass",
	"RG - Trail",
	"RG - Udagawa",
	"RaysDeLite",
	"Retreat",
	"RetreatHQ",
	"RiverVista",
	"Road",
	"Role Play",
	"Ronpa Mansion Area 5",
	"Ronpa Mansion Day",
	"Ronpa Mansion Day2",
	"Ronpa Mansion Day3",
	"Ronpa Mansion Day4",
	"Ronpa Mansion Night",
	"Ronpa Mansion Night2",
	"Ronpa Mansion Night3",
	"Ronpa Mansion Night4",
	"Ronpa mansion Haunted",
	"Ronpers Express",
	"RooftopAAI2",
	"RuinedCastle",
	"RuinedCourt",
	"Ruins Entrance",
	"SDR2 ISLAND",
	"SDR2 ISLAND2",
	"SDR2 ISLAND2 NIGHT",
	"SDR2 ISLAND3",
	"SDR2 ISLAND NIGHT",
	"SI - Bedroom",
	"SI - Class(sunset)",
	"SI - Class",
	"SI - Council1",
	"SI - Council2",
	"SI - Council3",
	"SI - Gym",
	"SI - Gym2",
	"SI - Hall",
	"SI - Hall2",
	"SI - Lockers",
	"SI - Nurse",
	"SI - Office",
	"SI - Pink",
	"SI - Roof",
	"SI - Roof2",
	"SI - School",
	"Seance",
	"SecretRoomsJFA",
	"SecurityCompanyTT",
	"ShipAAI2",
	"SkialForest",
	"Sky",
	"SkyDeck",
	"SoJCourt",
	"SoJDefendantLobby",
	"Somina Castle",
	"Somina Castle Night",
	"SpaceCourt",
	"SpaceCourtBlue",
	"SpaceCourtGreen",
	"SpaceCourtNormal",
	"SpaceCourtOrange",
	"SpaceCourtRainbow",
	"SpaceCourtRed",
	"SpaceCourtYellow",
	"SpacePort",
	"Spaceship",
	"StageAAI",
	"StageDisassembledAAI",
	"SteamBar",
	"SteamGarden",
	"SteamGovt",
	"SteamSquare",
	"SteamStreet",
	"Street",
	"SummerFestival",
	"SummerFestivalEvening",
	"TARDIS",
	"TEOS Lab",
	"TTAtmeyOffice",
	"TTBlueScreensInc",
	"TTDemasqueHideout",
	"TTHazakuraTemple",
	"TTHazakuraTempleInner",
	"TTKBSecurity",
	"TTLordlyTailor",
	"TTTenderLender",
	"TTTresBien",
	"TenderLenderTT",
	"Themis",
	"Titania",
	"TitaniaValley",
	"Togami Mansion",
	"TouhouCourt",
	"Tower",
	"Town",
	"Town Night",
	"Tr0LLc0urt",
	"TrainstationAA",
	"TresBienTT",
	"TrollCourt",
	"Twotorial Village",
	"Twotorial Village Night",
	"VC 1",
	"VLR",
	"VLR2.2",
	"VLR2.3",
	"VLR2",
	"VLR3",
	"VitaminSquareTT",
	"WEN",
	"WaitingRoomAAI",
	"WestAAI",
	"WinterPalaceAAI2",
	"WitchTrialCourt",
	"WitchtrialCourtHQ",
	"Witchwood",
	"WorldEmulator",
	"Wreckage (SG)",
	"Wrightagency",
	"Xmas",
	"Zetta",
	"animation",
	"apollojustice",
	"background",
	"basement",
	"birthday",
	"blackout",
	"chess",
	"chessw1",
	"chessw2",
	"chessw3",
	"chessw4",
	"christmas",
	"circus",
	"classtrial",
	"cofe",
	"courthouseofgods",
	"cruise",
	"cruise court",
	"custom",
	"custom1",
	"custom2",
	"custom3",
	"custom4",
	"custom5",
	"custom6",
	"custom7",
	"custom8",
	"custom9",
	"custom10",
	"daimoncourt",
	"default - Kopie",
	"default",
	"default_christmas",
	"defendantlobby",
	"defendantlobbyapollo",
	"detentioncenter",
	"doppler",
	"dr1stfloor",
	"dr1stfloordorms",
	"dr1stfloorhalls",
	"dr2ndfloor",
	"dr3rdfloor",
	"druq1stfloordorms",
	"druq2ndfloordorms",
	"dualdestinies",
	"dualdestiniesOG",
	"dungeon",
	"endless",
	"englishcourt",
	"forest",
	"gs4",
	"gs4night",
	"gs5",
	"hd",
	"inn",
	"investigationbando",
	"investigationsembassylobby",
	"investigationsgourdlake",
	"investigationsmilesoffice",
	"investigationsplaneair",
	"investigationsroyalcourt",
	"investigationstvroom",
	"investigationswestern",
	"investigationswitchtown",
	"island 1(uranus zone)",
	"lcourt",
	"legacy",
	"lobbyDGS-ENG",
	"lobbyDGS-JAP",
	"lobbyPLvsAA-ENG",
	"lobbyPLvsAA-LAB",
	"lobbySOJ",
	"magatama",
	"magatama1",
	"magatama2",
	"magatama3",
	"magatama4",
	"magatama5",
	"marblefade",
	"matrix",
	"matrixall",
	"matrixangry",
	"matrixangrysad",
	"matrixangrysurprised",
	"matrixhappy",
	"matrixhappyangry",
	"matrixhappysad",
	"matrixhappysurprised",
	"matrixsad",
	"matrixsadsurprised",
	"matrixsurprise",
	"mlp",
	"newcourt",
	"night (no lights)",
	"plvsaa",
	"policestation",
	"prisonvestigation",
	"sdr2classtrial",
	"sky",
	"sshope2ndfloorday(incident)",
	"sshope2ndfloorday",
	"sshope2ndfloornight(incident)",
	"sshope2ndfloornight",
	"sshopeday(incident)",
	"sshopeday",
	"sshopenight(incident)",
	"sshopenight",
	"thief",
	"thiefbash",
	"thiefpoint",
	"thiefpoisoning",
	"thiefprints",
	"thiefstab",
	"thiefsteal",
	"turnaboutstorm - Kopie",
	"turnaboutstorm",
	"vocalcourt",
	"witchtrialcourt"
];