export default [
    "01_Turnabout_Courtroom_-_Prologue.Mp3",
    "113 Confrontation ~ Presto 2009.Mp3",
    "114 Pursuit(Miles).Mp3",
    "3Dkh.Mp3",
    "Announce The Truth (Aa).Mp3",
    "Announce The Truth (Aj).Mp3",
    "Announce The Truth (Jfa).Mp3",
    "Announce The Truth (Miles).Mp3",
    "Announce The Truth (T&T).Mp3",
    "Crises Of Fate.Mp3",
    "Forgotten Legend.Mp3",
    "Ghost Trick - 4 Minutes Before Death.Mp3",
    "Ghost Trick - Countdown.Mp3",
    "Ghost Trick - The World Of The Dead.Mp3",
    "Godot - The Fragrance Of Dark Coffee.Mp3",
    "Great Revival ~ Franziska Von Karma.Mp3",
    "Great Revival ~ Miles Edgeworth.Mp3",
    "Hotline Of Fate.Mp3",
    "Interesting People.Mp3",
    "Logic_And_Trick.Mp3",
    "Luke Atmey ~ I Just Want Love.Mp3",
    "Mystery Skulls - Ghost.Mp3",
    "Mystery Skulls - Money.Mp3",
    "Noisy People.Mp3",
    "Objectiom(Aj).Mp3",
    "Objection (Aa).Mp3",
    "Objection (Jfa).Mp3",
    "Objection (Miles).Mp3",
    "Objection (T&T).Mp3",
    "Others ~ Guilty Love.Mp3",
    "Prelude(Aa).Mp3",
    "Prelude(Aj).Mp3",
    "Pursuit (Aa) - Variation.Mp3",
    "Pursuit (Aa).Mp3",
    "Pursuit (Aj).Mp3",
    "Pursuit (Ds).Mp3",
    "Pursuit (Jfa) - Variation.Mp3",
    "Pursuit (Jfa).Mp3",
    "Pursuit (T&T) - Variation.Mp3",
    "Pursuit (T&T).Mp3",
    "Pursuit ~ I Want To Find The Truth (Orchestra).Mp3",
    "Questioning Aa (Allegro).Mp3",
    "Questioning Aa (Moderato).Mp3",
    "Questioning Aj (Allegro).Mp3",
    "Questioning Aj (Moderato).Mp3",
    "Questioning Jfa (Allegro).Mp3",
    "Questioning Jfa (Moderato).Mp3",
    "Questioning T&T (Allegro).Mp3",
    "Questioning T&T (Moderato).Mp3",
    "Sin.Mp3",
    "Speak Up, Pup!.Mp3",
    "Suspense (Aa).Mp3",
    "The Great Truth Burglar.Mp3",
    "Trans.Mp3",
    "Trial (Aa).Mp3",
    "Trial (Aj).Mp3",
    "Trial (Miles).Mp3",
    "~Stop.Mp3",
];
