name: Formatting

on:
  push:
    branches:
    - master
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '14'
        cache: 'npm'
    - name: Prettier Action
      uses: creyD/prettier_action@v4.3
      with:
        same_commit: false
        prettier_options: --write **/*.js
